dist: xenial
language: node_js

env:
    - MAPBOX_API_TOKEN=pk.eyJ1IjoiYmN3YXJkIiwiYSI6ImNrMjVrYWpnbjA2dDAzY3F5NmJpeDBzczcifQ.XnzzlO2ke7qbAjvY--m9Pw

node_js:
    - '8'
    - '10'

cache:
    directories:
        - 'node_modules'
services:
    - xvfb

env:
    - CXX=g++-6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-6
            - libgles2-mesa-dev
            - libgbm-dev
            - libllvm3.9
            - libprotobuf-dev
            - libxxf86vm-dev

install:
    - npm install coveralls --skip-lock

script:
    - npm run test

after_script:
    - cat ./tests/coverage/lcov.info | coveralls
